# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RecycleHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecycleHelper
  pod 'Firebase/Core' 
  pod 'Firebase/MLVision' 
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/Analytics'

  target 'RecycleHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecycleHelperUITests' do
    # Pods for testing
  end

end
