# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecycleHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecycleHelper
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'
    pod 'SwipeCellKit'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Database'
    pod 'FirebaseUI/Database', '~> 8.0'

  target 'RecycleHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecycleHelperUITests' do
    # Pods for testing
  end

end
