# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RecycleHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecycleHelper
  pod 'Firebase/Core'
  # On-device API
  pod 'Firebase/MLVisionTextModel'
  # Cloud-based API
  pod 'Firebase/MLVision'
  
  target 'RecycleHelperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RecycleHelperUITests' do
    # Pods for testing
  end

end
